# Lesson 7

In [1]:
import numpy as np

# 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [2]:
# я не совсем поняла про использование intercept и повторила все методы, которые мы рассмотрели на лекции. 
# что подразумевалось в задании?

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks= np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

# количество наблюдений
n = len(zp)

In [4]:
b_1 = (np.mean(zp * ks) - np.mean(zp) * np.mean(ks)) / (np.mean(zp**2) - np.mean(zp) ** 2)
b_1

2.620538882402765

In [5]:
a_1 = np.mean(ks) - b_1 * np.mean(zp)
a_1

444.1773573243596

In [6]:
b_2 = (n*(np.sum(zp*ks)) - (np.sum(zp)*np.sum(ks)))/(n*(np.sum(zp**2))-((np.sum(zp)**2)))
b_2

2.6205388824027653

In [7]:
a_2 = np.mean(ks) - b_2*np.mean(zp)
a_2

444.17735732435955

In [8]:
X = zp.reshape((10,1))
y = ks.reshape((10,1))

In [9]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T@y)
B

array([[5.88982042]])

# 2

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [10]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [11]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [12]:
def mse_(B1,y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

In [13]:
alpha = 1e-6
alpha

1e-06

In [14]:
B1 = 1

In [15]:
n = 5

In [16]:
for i in range (10):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    print(f'B1={B1}')

B1=1.2694604
B1=1.52407180741344
B1=1.764652496765392
B1=1.9919756504176396
B1=2.206771843435465
B1=2.4097313915223726
B1=2.601506569568584
B1=2.7827137079433095
B1=2.9539351732679022
B1=3.115721240035732


In [17]:
for i in range (10000):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%1000==0:
        print(f'Iteration: {i}, B1 = {B1}, mse = {mse_(B1)}')

Iteration: 0, B1 = 3.268591859093827, mse = 151173.6613142009
Iteration: 1000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 2000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 3000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 4000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 5000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 6000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 7000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 8000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 9000, B1 = 5.889820420132681, mse = 56516.85841571941


## 3

В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента? 

Критерий Лапласа используется, если известна дисперсия генеральной совокупности, если нет - таблица критических точек распределения Стьюдента

# 4

In [18]:
B1 = 0.1
B0 = 0.1

In [19]:
def mse_(B0,B1,y=y,X=X,n=10):
    return np.sum((B0+B1*X-y)**2)/n

In [22]:
for i in range (10000000):
    y_pred = B0 + B1*X
    B0 -= alpha*(2/n)*np.sum((y_pred - y))
    B1 -= alpha*(2/n)*np.sum((y_pred - y)*X)
    if i%500000==0:
        print(f'Iteration: {i}, B0= {B0}, B1 = {B1}, mse = {mse_(B0,B1)}')                    

Iteration: 0, B0= 431.4368859638349, B1 = 2.7143143845021864, mse = 6511.588990614024
Iteration: 500000, B0= 436.5060959794563, B1 = 2.677002757560722, mse = 6485.341937393006
Iteration: 1000000, B0= 439.5583562720048, B1 = 2.6545367723257716, mse = 6475.8261853443855
Iteration: 1500000, B0= 441.39617574775053, B1 = 2.641009608437617, mse = 6472.376291892066
Iteration: 2000000, B0= 442.5027590996847, B1 = 2.632864665718778, mse = 6471.125548412006
Iteration: 2500000, B0= 443.1690523515301, B1 = 2.6279604528000267, mse = 6470.6720969432745
Iteration: 3000000, B0= 443.57023920892993, B1 = 2.6250075401546655, mse = 6470.507700136293
Iteration: 3500000, B0= 443.81180085483965, B1 = 2.6232295396402314, mse = 6470.448098807338
Iteration: 4000000, B0= 443.9572493601554, B1 = 2.622158974334629, mse = 6470.426490611436
Iteration: 4500000, B0= 444.0448264571904, B1 = 2.621514368180393, mse = 6470.418656656411
Iteration: 5000000, B0= 444.09755816391225, B1 = 2.6211262395048935, mse = 6470.4158164