# Lesson 7

In [1]:
import numpy as np

# 1

Даны значения величины заработной платы заемщиков банка (zp) и значения их поведенческого кредитного скоринга (ks): zp = [35, 45, 190, 200, 40, 70, 54, 150, 120, 110], ks = [401, 574, 874, 919, 459, 739, 653, 902, 746, 832]. Используя математические операции, посчитать коэффициенты линейной регрессии, приняв за X заработную плату (то есть, zp - признак), а за y - значения скорингового балла (то есть, ks - целевая переменная). Произвести расчет как с использованием intercept, так и без.

In [2]:
# я не совсем поняла про использование intercept и повторила все методы, которые мы рассмотрели на лекции. 
# что подразумевалось в задании?

In [3]:
zp = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
ks= np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

# количество наблюдений
n = len(zp)

In [4]:
b_1 = (np.mean(zp * ks) - np.mean(zp) * np.mean(ks)) / (np.mean(zp**2) - np.mean(zp) ** 2)
b_1

2.620538882402765

In [5]:
a_1 = np.mean(ks) - b_1 * np.mean(zp)
a_1

444.1773573243596

In [6]:
b_2 = (n*(np.sum(zp*ks)) - (np.sum(zp)*np.sum(ks)))/(n*(np.sum(zp**2))-((np.sum(zp)**2)))
b_2

2.6205388824027653

In [7]:
a_2 = np.mean(ks) - b_2*np.mean(zp)
a_2

444.17735732435955

In [8]:
X = zp.reshape((10,1))
y = ks.reshape((10,1))

In [9]:
X = np.hstack([np.ones((10,1)), X])

In [10]:
B = np.dot(np.linalg.inv(np.dot(X.T,X)),X.T@y)
B

array([[444.17735732],
       [  2.62053888]])

# 2

Посчитать коэффициент линейной регрессии при заработной плате (zp), используя градиентный спуск (без intercept).

In [11]:
X = np.array([35, 45, 190, 200, 40, 70, 54, 150, 120, 110])
X

array([ 35,  45, 190, 200,  40,  70,  54, 150, 120, 110])

In [12]:
y = np.array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])
y

array([401, 574, 874, 919, 459, 739, 653, 902, 746, 832])

In [13]:
def mse_(B1,y=y,X=X,n=10):
    return np.sum((B1*X-y)**2)/n

In [14]:
alpha = 1e-6
alpha

1e-06

In [15]:
B1 = 1

In [16]:
n = 5

In [17]:
for i in range (10):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    print(f'B1={B1}')

B1=1.2694604
B1=1.52407180741344
B1=1.764652496765392
B1=1.9919756504176396
B1=2.206771843435465
B1=2.4097313915223726
B1=2.601506569568584
B1=2.7827137079433095
B1=2.9539351732679022
B1=3.115721240035732


In [18]:
for i in range (10000):
    B1 -=alpha*(2/n)*np.sum((B1*X-y)*X)
    if i%1000==0:
        print(f'Iteration: {i}, B1 = {B1}, mse = {mse_(B1)}')

Iteration: 0, B1 = 3.268591859093827, mse = 151173.6613142009
Iteration: 1000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 2000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 3000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 4000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 5000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 6000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 7000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 8000, B1 = 5.889820420132681, mse = 56516.85841571941
Iteration: 9000, B1 = 5.889820420132681, mse = 56516.85841571941


## 3

В каких случаях для вычисления доверительных интервалов и проверки статистических гипотез используется таблица значений функции Лапласа, а в каких - таблица критических точек распределения Стьюдента? 

Критерий Лапласа используется, если известна дисперсия генеральной совокупности, если нет - таблица критических точек распределения Стьюдента